# changelog:
#   categories:
#     - title: "✨ New Features"
#       labels:
#         - enhancement
#     - title: "🚀 Improvements"
#       labels:
#         - improvement
#     - title: "🐞 Bug Fixes"
#       labels:
#         - bug
#     - title: "⚠️ Breaking Changes"
#       labels:
#         - breaking-change
#     - title: "🔀 Pull requests"
#       labels: []
#   exclude:
#     issues: false # Ensure issues are included
#     pull_requests: false # Ensure PRs are included

# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
